name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build all projects
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build the project
        run: sbt compile

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build the project
        run: sbt test

  format:
    name: Format scala source code
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check formatting
        run: sbt scalafmtCheckAll

  lint:
    name: Lint via scalafix
    runs-on: ubuntu-20.04
    env:
      COURSIER_CACHE: ~/scalafix-cache
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache scalafix
        uses: actions/cache@v2
        with:
          path: ${{ env.COURSIER_CACHE }}
          key: scalafix-cache
      - name: Run scalafix checks
        run: sbt "scalafixAll --check"
